name: 'Infra-CI-Pipeline'

on: 
  push:
    paths:
      - 'terraform/**'
      - '.github/workflows/ci-infra.yml'

defaults:
  run:
    shell: bash
    
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1   
              
    - name: Terraform-Lint
      id: fmt
      run: terraform fmt -recursive -check -diff

  vulnerability_scanning:
    name: Vulnerability Scan
    runs-on: ubuntu-latest
    needs: [linting]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Static check infrastructure using tfsec
      id: tfsec
      run: |
        wget https://github.com/aquasecurity/tfsec/releases/download/`echo "$(curl https://api.github.com/repos/aquasecurity/tfsec/releases/latest | jq -r .tag_name)"`/tfsec-linux-amd64 -O tfsec && chmod +x tfsec
        ./tfsec --exclude-downloaded-modules

  validation:
    name: Validation
    runs-on: ubuntu-latest
    needs: [vulnerability_scanning]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1   
              
    - name: rm Init
      run: terraform -chdir=terraform init -backend=false

    - name: Terraform Validation
      id: validate-platform
      run: terraform -chdir=terraform validate -json