name: "Deployment"

on:
  push:
    branches:
      - main

env:
  PKR_VAR_project_id: root-amulet-315711
  PKR_VAR_zone: "us-central1-a" 

defaults:
  run:
    shell: bash


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: addnab/docker-run-action@v3
      with:
        image: openjdk:11.0.11-jdk-oracle
        options: -v ${{ github.workspace }}:/workspace
        run: |
          cd /workspace
          ./mvnw package

    - uses: actions/upload-artifact@v2
      with:
        name: app_jar
        path: target/spring-petclinic-rest-2.4.2.jar

  packing:
    name: Packing
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download build jar
      uses: actions/download-artifact@v2
      with:
        name: app_jar
        path: target/

    - name: Install Packer
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install packer

    - name: Checking Lint
      run: packer fmt -check -diff packer.pkr.hcl

    - name: Init packer
      run: packer init .

    - name: Validate packer file
      run: packer validate packer.pkr.hcl

    - name: Setup secret file
      id: write_secret_file
      uses: timheuer/base64-to-file@v1
      with:
        fileName: 'creds.json'
        encodedString: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}

    - name: Build image
      run: |
        export GOOGLE_APPLICATION_CREDENTIALS=${{ steps.write_secret_file.outputs.filePath }}
        packer build packer.pkr.hcl

    - name: Upload packer-manifest.json
      uses: actions/upload-artifact@v2
      with:
        name: packer-manifest
        path: packer-manifest.json

    - name: cat packer-manifest.json
      run: cat packer-manifest.json