name: 'Test'

on: 
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Print ID Token
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2