name: 'Test'

on: 
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  test:
    name: create test artifact
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Create artifact
      run: |
        curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=test" >> input.txt
        IN=$(cat input.txt | jq .value)
        parts=$(echo $IN | tr "." "\n")

        for part in $parts
        do
            echo "> [$part]"
        done
    
    - name: wait
      run: sleep 3600