name: 'Test'

on: 
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  test:
    name: create test artifact
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Create artifact
      run: |
        curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=test" >> test.txt
        echo ${{ secrets.GITHUB_TOKEN }} > test.txt
    
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: test
        path: test.txt