name: "Downloader"

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Build Backend Image"
      - "Build Frontend Image"
      - "Build Postgres Image"
    branches: [main]
    types:
      - completed

defaults:
  run:
    shell: bash


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Download backend artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: deploy.yml
        workflow_conclusion: success
        branch: main
        name: packer-manifest
        path: backend
    - name: Print
      run: cat backend/packer-manifest.json

    - name: Download frontend artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: deploy-frontend.yml
        workflow_conclusion: success
        branch: main
        name: packer-manifest
        path: frontend
    - name: Print
      run: cat frontend/packer-manifest.json

    - name: Download postgres artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: deploy-postgres.yml
        workflow_conclusion: success
        branch: main
        name: packer-manifest
        path: postgres
    - name: Print
      run: cat postgres/packer-manifest.json
